version: '3.4'

services:
  urborexpertapp:
    image: urborexpertapp
    container_name: urborexpertapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      # for ai server
      - '3040:3000'
    restart: always